### ISSUE TITLE
Mavenise

### ISSUE THREAD

**Issue by Shusshu** [ManuelPeinado/FadingActionBar#1]
I see you have pom's in other projects you made on github.
Could you also mavenise this one?

**Comment by ManuelPeinado** [comment]
Yes that's first is my TODO list.

**Comment by ManuelPeinado** [comment]
Done!

**Comment by Shusshu** [comment]
Yeah thanks !

Benoit Billington

**Comment by ManuelPeinado** [comment]
Might not be available in Maven central until after a couple of hours, I just uploaded it to Sonatype OSS
