### ISSUE TITLE
Using only with resource ids. 

### ISSUE THREAD

**Issue by tasomaniac** [ManuelPeinado/FadingActionBar#2]
Your lib is great but it can be initialized with only resource ids. And you are using setContentView of the activity. So this cannot be used with fragments. Maybe you should have another helper method in which ScrollView and HeaderView are the actual parameters not the ids.

**Comment by ManuelPeinado** [comment]
Thanks for the great suggestions, these are definitely  things I plan to add soon.

**Comment by ManuelPeinado** [comment]
Hey, just a question. 

Can you tell me a good use case for using the fading action bar pattern with fragments? I can't think of any, and until I do I don't feel like adding support for it. 

Thanks!

**Comment by tasomaniac** [comment]
I just have a tablet layout with two pane. You are right when it is two
pane it is not logical to have fading layout. But you have to use fragments
if you have two pane layout. So in phones I have an activity for the detail
pane which only adds the fragment to the activity. You know this is the
classic master detail app code. I am only enabling fading action bar in
this phone layout but since I use fragments, I have to make this work on
fragments.

Besides fragments are everywhere nowadays. Even there is no tablet layout
there can be an activity just with a fragment.

**Comment by ManuelPeinado** [comment]
Yeah that makes sense. I'll be releasing v2 soon with your suggested changes. Thanks!

**Comment by cyrilmottier** [comment]
Generally speaking it's usually a bad idea to force the content of the `Activity` or `Fragment` as you currently do in the library. Indeed, the content is not up to the library but up to the developer/client. As a consequence, I am convinced, `FadingActionBarHelper` should not use `setContentView(int)` for instance.

**Comment by tasomaniac** [comment]
I think so as well the library should get the views and the actionbar and
then do the animation.

**Comment by ManuelPeinado** [comment]
Thanks for your help guys. I think I agree with your thoughts on this, I'll find a better way and release it as part of v2

**Comment by ManuelPeinado** [comment]
I've released v2 which can be used with fragments (see sample) and which doesn't highjack Activity#setContentView
