### ISSUE TITLE
Can headerview be longer then screen height?

### ISSUE THREAD

**Issue by joakim5937x** [ManuelPeinado/FadingActionBar#25]
Im trying to make a header that sometimes is longer then my screen height, but for some reason the screen height of my device seems to be the maximum height the headerview can be.

Is there any workarounds for this? To enable the headerviews height to become greater than the height?

**Comment by ManuelPeinado** [comment]
If the header is longer than the screen then you have no access to the content, which means that you can't scroll and  the pattern makes no sense. Try to make your images smaller, otherwise I don't recommend you use this library, it might not be a good fit for your needs.

**Comment by joakim5937x** [comment]
The scroll isnt really a problem if you make the header clickable, like described here: https://github.com/ManuelPeinado/FadingActionBar/issues/8#issuecomment-20191452
By doing that you could still access both the header and the body content even if the header is longer then the screen.

Was just wondering if max height was something that you could easily modify.

**Comment by ManuelPeinado** [comment]
I'm not enforcing a max height for the header in the library, I guess it's
just the layout system clamping the view it to make it fit in the available
height. If you want to have a view that's larger than it's containing
window I think you'll have to use a ScrollView
