### ISSUE TITLE
error on onAttach

### ISSUE THREAD

**Issue by giwrgos88** [ManuelPeinado/FadingActionBar#36]
Hello i'm having a small problem with the library. i have used the example of the NavigationDrawer in my project and instead of having the switch of the fragment in the activity i have it inside to the PlaceholderFragment which extends a Fragment. when i click on a row is throw me this error message 02-13 00:25:40.668: E/AndroidRuntime(23175):   at com.georgiospanayi.fragments.SingleFragment.onAttach(SingleFragment.java:45)

How i can solve it? 
Here a small example of my code which is inside the PlaceholderFragment

// update the main content by replacing fragments
        Fragment fragment = new SingleFragment();
        Bundle args = new Bundle();
        args.putString(SingleFragment.ARG_IMAGE_RES, this.list.get(position).get_Image());
        fragment.setArguments(args);

```
    FragmentManager fragmentManager = this.main_activity.getFragmentManager();
    fragmentManager.beginTransaction().setTransition(FragmentTransaction.TRANSIT_FRAGMENT_FADE).replace(R.id.container, fragment).commit();
```

**Comment by ManuelPeinado** [comment]
Hi, as I said in my other response I won't be able to look into this in the next 3 or so weeks.

Sorry.
