### ISSUE TITLE
[SOLVED] Transparent actionbar is not working on fragment

### ISSUE THREAD

**Issue by giwrgos88** [ManuelPeinado/FadingActionBar#38]
Hello everyone, i'm trying to use the fadingActionBar on my app and i used the code of the SampleFragment.java but i'm having a small issue. as you can see in the image the actionbar is not transparent. what i'm doing wrong? thank you
![screenshot_2014-02-25-12-03-41](https://f.cloud.github.com/assets/3164113/2257199/273e6574-9e15-11e3-8ef9-7758cf2e40e3.png)

**Comment by mkubenka** [comment]
Did you use AppTheme.TranslucentActionBar in AndroidManifest.xml?

**Comment by giwrgos88** [comment]
any help?

**Comment by ManuelPeinado** [comment]
Hi, thanks for using the library. 

Unfortunately I'm overcommitted at the moment and can't devote virtually any time to my OSS projects, sorry. 

The only thing that I can recommend is that you try to find any differences between the fragments sample and your own code, there has to be something. 

I will have some spare time in about 3 weeks, if you can wait then I'll be able to help you then.

**Comment by giwrgos88** [comment]
UPDATE: Solution
Instead of trying to add the Translucent on fragment im creating a new activity from the fragment on that activity i'm using the Translucent. 
So if anyone wants to have an activity that has a fragment which contains a list and wants when user clicks on the item to open it on a single fragment he/she has to create a new activity with a single fragment and addd the Translucent on that activity.

**Comment by netcyrax** [comment]
Found another solution to the same issue; making the action bar overlay. It is described here:
https://developer.android.com/training/basics/actionbar/overlaying.html

If you want this fix in a single activity, just call:
        supportRequestWindowFeature(Window.FEATURE_ACTION_BAR_OVERLAY);
