### ISSUE TITLE
HoloEverywhere

### ISSUE THREAD

**Issue by fabriciomassula** [ManuelPeinado/FadingActionBar#4]
Hello,

I would like to use it with HoloEverywhere library (https://github.com/Prototik/HoloEverywhere). When trying to use it, the library send me an error message saying that my activity should be an instance of SherlockActivity (and it is the HoloEverywhere activity...).

Thnks and congrats for yout great work!!

**Comment by ManuelPeinado** [comment]
Thanks!

Your activity must indeed derive from SherlockActivity, otherwise how will you implement a backwards-compatible action bar?

**Comment by fabriciomassula** [comment]
Hello,

As you can see on HoloEverywhere basic migration guide (https://github.com/Prototik/HoloEverywhere/wiki/Basic-migration-on-HoloEverywhere), while using the library, we always extend our activities from ¨org.holoeverywhere.app.***Activity¨ and the library takes care of compatibility issues with ActionBarSherlock.

Thnks

**Comment by ManuelPeinado** [comment]
I see. Let me think of something, I'll get back to you.

**Comment by ManuelPeinado** [comment]
I've just pushed a fix to your problem to the "dev" branch. With this fix the library will work with any activity that implements a method called "getSupportActionBar", regardless of whether it derives from any of the ABS activities.

Please test it and tell me if it works for you, before I integrate it with the master branch.
