### ISSUE TITLE
NoSuchMethodError FAB with ActionBarSherlock on 2.x

### ISSUE THREAD

**Issue by uint16** [ManuelPeinado/FadingActionBar#40]
I used to use FAB with actionbarsherlock on 2.x applications, but lately it doesn't work on 2.x again, (API 8 to be specific)...

03-12 21:13:46.263: E/AndroidRuntime(331): FATAL EXCEPTION: main
03-12 21:13:46.263: E/AndroidRuntime(331): java.lang.NoSuchMethodError: android.app.Activity.getActionBar
03-12 21:13:46.263: E/AndroidRuntime(331):  at com.manuelpeinado.fadingactionbar.FadingActionBarHelper.initActionBar(FadingActionBarHelper.java:30)

full log at http://pastebin.com/58SSin4V

Can someone please confirm this is not an issue with FAB

**Comment by ManuelPeinado** [comment]
Hi!

You seem to be using the native version of FadingActionBarHelper, which is in the com.manuelpeinado.fadingactionbar package.

Please make sure you use the version in com.manuelpeinado.fadingactionbar.extras.actionbarsherlock, it should solve your issue.
