### ISSUE TITLE
java.lang.NoSuchMethodError: android.app.Activity.getActionBar on Android 2.3

### ISSUE THREAD

**Issue by s0nerik** [ManuelPeinado/FadingActionBar#48]
I've got java.lang.NoSuchMethodError: android.app.Activity.getActionBar on Android 2.3.
I'm using ActionBarCompat. My build.gradle:
dependencies {
    ...
    compile 'com.github.manuelpeinado.fadingactionbar:fadingactionbar-abc:3.1.2'
}

**Comment by ManuelPeinado** [comment]
Maybe you are importing com.manuelpeinado.fadingactionbar.FadingActionBarHelper instead of com.manuelpeinado.fadingactionbar.extras.actionbarcompat.FadingActionBarHelper?

This is a big pitfall, maybe I should add a "Troubleshooting" section to the README

**Comment by s0nerik** [comment]
Thanks a lot. Importing com.manuelpeinado.fadingactionbar.extras.actionbarcompat.FadingActionBarHelper instead of com.manuelpeinado.fadingactionbar.FadingActionBarHelper actually helped.
