### ISSUE TITLE
notifyDataSetChanged() in List combined with FadingActionBar destroys view

### ISSUE THREAD

**Issue by Zordid** [ManuelPeinado/FadingActionBar#7]
I got a problem with a ListView in combination with the FadingActionBar.
Once every minute I recalculate the displayed data and call notifyDataSetChanged on the associated adapter.

But every time this happens, the header image gets visible and is visible THROUGH the scrolled list. Only if the list is at its top position, everything stays fine.

![screenshot_2013-06-24-22-33-13](https://f.cloud.github.com/assets/4798822/698101/f97bf66a-dd0d-11e2-8fd6-0633bb253b35.png)

Do you have any idea why this happens?
Thanks!

**Comment by Zordid** [comment]
I tried several different approaches now - even with the most simple ListView, the problem stays.
Simply call notifyDataSetChanged() to force a redraw always re-displays the header image no matter whether it should be visible or not. After that happened and you scroll, the image is misplaced - it still moves, but it is not at the correct position any more.
Scrolling to the top of the list and waiting for my next notifyDataSetChanged fixes the display again.

This is really a serious bug in the current implementation, I sincerely hope this can be fixed? Thanks!

**Comment by Zordid** [comment]
I managed to find out that apparently the calculation of the `mHeaderContainer` vertical offset is off because after a refresh occurred, the ListView resets its header to position 0! 
Within the method `addParallaxEffect`, I logged the absolute positions of top and bottom of mHeaderContainer and whenever the notification for changed data was issued, suddenly the top went back to 0....

**Comment by ManuelPeinado** [comment]
This is a serious problem indeed, thanks a lot for reporting it. I'll look into it ASAP, your insight about the probably cause of the issue will certainly help,

**Comment by Zordid** [comment]
No problem! I got the top image fixed by placing:

```
mHeaderContainer.setTop(-dampedScroll);
mHeaderContainer.setBottom(-dampedScroll + mLastHeaderHeight);
```

instead of

```
mHeaderContainer.offsetTopAndBottom(offset);
```

But the background image still gives me a headache. I tried the same simple approach there, but that did not work. Don't know why... :-)
I also don't get why the refresh of the list messes around with the positions of the header view...
Maybe it's version related? I got 4.1.2 running on an HTC One.

Thanks!

**Comment by Zordid** [comment]
Okay, I got "my" fix running now.
Of course, I am not sure whether this works on all devices and I also don't know why exactly you used the offsetTopAndBottom methods and not the absolute setTop/setBottom methods. But with this new addParallaxEffect method, the described bug seems gone:

```
private void addParallaxEffect(final int scrollPosition) {
    float damping = mUseParallax ? 0.5f : 1.0f;
    int dampedScroll = (int) (scrollPosition * damping);
    mHeaderContainer.setTop(-dampedScroll);
    mHeaderContainer.setBottom(-dampedScroll + mLastHeaderHeight);

    if (mListViewBackgroundView != null) {
        int postion = mLastHeaderHeight - scrollPosition;
        int height = mListViewBackgroundView.getHeight();
        mListViewBackgroundView.setTop(postion);
        mListViewBackgroundView.setBottom(postion + height);
    }

}
```

**Comment by ManuelPeinado** [comment]
Thanks for the fix, I'll include it as soon as I have some free time.

**Comment by Zordid** [comment]
Hi Manuel, okay - my "fix" has got a problem in backwards compatibility. setTop and other methods have been added in API 11 only - and its documentation says 

> Sets the top position of this view relative to its parent. This method is meant to be called by the layout system
> and should not generally be called otherwise, because the property may be changed at any time by the layout.

This is really bad. So, my changes are not the desired fix for the problem. But maybe you can find a better solution that keeps using `offsetTopAndBottom`; maybe there has to be a check for the current value before calling it?

**Comment by ManuelPeinado** [comment]
Haven't been able to look at this yet, thanks for your patience.

**Comment by tinyao** [comment]
I also encounter this. temporarily, I use Zordid's approach.  Did this issue fixed for pre API 11?

**Comment by ManuelPeinado** [comment]
Hey guys. Just to let you know that I've been trying to find a workaround to setTop / setBottom but so far without success. If you have any ideas I'll really appreciate it.

**Comment by mozarcik** [comment]
Check dev branch because there is new fix to this problem. Still not merged into master.
